apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scale-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scale-app
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
