apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-web-app-replicaset
  labels:
    app: node-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
        - name: node-web-app
          image: node-web-app:latest
          ports:
            - containerPort: 3000
