apiVersion: v1
kind: Service
metadata:
  name: web-app-service-v1
  namespace: web-v1
spec:
  selector:
    app: web-app-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
