apiVersion: v1
kind: Service
metadata:
  name: web-app-service-v2
  namespace: web-v2
spec:
  selector:
    app: web-app-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
