apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment-v2
  namespace: web-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-v2
  template:
    metadata:
      labels:
        app: web-app-v2
    spec:
      containers:
        - name: web-app
          imagePullPolicy: IfNotPresent
          image: web-app:v2

          ports:
            - containerPort: 3000
