apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment-v1
  namespace: web-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-v1
  template:
    metadata:
      labels:
        app: web-app-v1
    spec:
      containers:
        - name: web-app
          imagePullPolicy: IfNotPresent
          image: web-app:v1

          ports:
            - containerPort: 3000
